import fs from 'node:fs/promises';

import Profile from '../models/Profile.js';

import asyncHandler from '../utils/asyncHandler.js';

import {
  generateHeroCandidates,
} from '../services/imageAI.js';


// ============================================================
// GENERATE HERO IMAGES
// ============================================================

/**
 * POST /api/hero/generate
 *
 * Protected route.
 *
 * Receives:
 *
 * multipart/form-data
 * image = uploaded image
 *
 * Returns:
 *
 * {
 *   candidates: [...]
 * }
 */

export const generateHeroImages = asyncHandler(
  async (req, res) => {

    // --------------------------------------------------------
    // Make sure an image was uploaded
    // --------------------------------------------------------

    if (!req.file) {
      return res.status(400).json({
        message: 'Please upload an image.',
      });
    }


    let result;

    try {

      console.log(
        `[Hero AI] Processing: ${req.file.originalname}`
      );


      // ------------------------------------------------------
      // Send uploaded image to AI service
      // ------------------------------------------------------

      result = await generateHeroCandidates(
        req.file.path
      );


      console.log(
        `[Hero AI] Generated ${result.candidates.length} candidates`
      );


      // ------------------------------------------------------
      // Return candidates to Admin Panel
      // ------------------------------------------------------

      return res.status(200).json({
        success: true,

        candidates: result.candidates,
      });

    } catch (error) {

      console.error(
        '[Hero AI] Generation failed:',
        error
      );


      return res.status(500).json({
        message:
          error?.message ||
          'Failed to generate AI hero images.',
      });

    } finally {

      // ------------------------------------------------------
      // Delete the original temporary upload
      // ------------------------------------------------------

      try {

        await fs.unlink(req.file.path);

      } catch (error) {

        /*
         * Ignore missing-file errors.
         */

        if (error.code !== 'ENOENT') {

          console.error(
            '[Hero AI] Could not delete temporary upload:',
            error.message
          );

        }
      }
    }
  }
);


// ============================================================
// SELECT HERO IMAGE
// ============================================================

/**
 * POST /api/hero/select
 *
 * Protected route.
 *
 * Body:
 *
 * {
 *   url: "/uploads/ai/hero-clean-123.png"
 * }
 */

export const selectHeroImage = asyncHandler(
  async (req, res) => {

    const { url } = req.body;


    // --------------------------------------------------------
    // Validate URL
    // --------------------------------------------------------

    if (!url || typeof url !== 'string') {

      return res.status(400).json({
        message: 'Image URL is required.',
      });

    }


    const cleanUrl = url.trim();


    if (!cleanUrl) {

      return res.status(400).json({
        message: 'Image URL cannot be empty.',
      });

    }


    // --------------------------------------------------------
    // Security check
    //
    // Only allow images generated by our AI image directory.
    // --------------------------------------------------------

    if (!cleanUrl.startsWith('/uploads/ai/')) {

      return res.status(400).json({
        message:
          'Invalid hero image URL.',
      });

    }


    // --------------------------------------------------------
    // Update Profile
    // --------------------------------------------------------

    const profile =
      await Profile.findOneAndUpdate(
        {},

        {
          avatarUrl: cleanUrl,
        },

        {
          new: true,
          upsert: true,
          setDefaultsOnInsert: true,
          runValidators: true,
        }
      );


    // --------------------------------------------------------
    // Response
    // --------------------------------------------------------

    return res.status(200).json({
      success: true,

      message:
        'Hero image selected successfully.',

      profile,
    });
  }
);